Repository AY2324S2-CS2103T-T17-1/tp, pull requests merged in 2024-03, with the labels that each got.

#6 v1.1 update site
  .gitignore
  README.md
  docs/AboutUs.md
  docs/_config.yml
  docs/images/camille-readbean.png
  docs/images/giselletan.png
  docs/images/theodorekooo.png
  docs/images/vannykin.png
  docs/images/vatsalvitosh.png
  docs/index.md
Labels: type.Task, priority.High

#9 Update developer guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#10 Added in user stories
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#12 Added in the use cases UC01 - UC04
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#30 Update DG use cases
  docs/DeveloperGuide.md
Labels: type.Task

#36 Update user guide link in help command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, severity.Medium

#43 Update delete command in developer guide
  docs/DeveloperGuide.md
  docs/images/DeleteActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
Labels: type.Task, priority.High

#45 Update DeleteCommand to account for empty list
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: type.Enhancement, priority.Medium

#46 Add puml files and images of view command diagrams
  docs/diagrams/ViewActivityDiagram.puml
  docs/diagrams/ViewObjectDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/ViewActivityDiagram.png
  docs/images/ViewSequenceDiagram.png
Labels: type.Enhancement, type.Task, priority.High

#48 Update help command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/helpWindow.png
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Story, priority.High

#49 Add basic model and test for appointments
  build.gradle
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/client/Client.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
Labels: type.Epic, type.Story, priority.High

#52 Fix page breaks
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
Labels: type.Task, type.Bug, priority.High

#54 Ug find tag and view
  docs/UserGuide.md
  docs/images/FindTagDisabledResult.png
  docs/images/FindTagDisabledSchizophrenicResult.png
Labels: type.Story, type.Task, priority.Medium

#56 Schedule and Unschedule command
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/helpWindow.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/UnscheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/UnscheduleCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/resources/view/ClientListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: type.Epic, type.Enhancement, priority.High, severity.VeryLow
