Repository AY2324S2-CS2103T-T17-1/tp, pull requests merged in 2024-04, with the labels that each got.

#58 Branch add note field
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/Note.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/resources/view/ClientListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateClientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalClientsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditClientDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/ClientUtil.java
  src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: priority.High

#57 Added tests for the find-tag command.
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: priority.High

#61 Bump MainApp verison number to v1.3
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, severity.Low

#124 Specify name format in add command
  docs/UserGuide.md
Labels: severity.Low, type.DocumentationBug

#123 Update UI images in UG
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  docs/images/helpWindow.png
Labels: severity.VeryLow

#129 Change delete to del in DG
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
Labels: severity.VeryLow, type.DocumentationBug

#130 Update known issues with adding and editing clients
  docs/UserGuide.md
Labels: severity.VeryLow, type.FunctionalityBug

#126 Specify duplicate appointments allowed
  docs/UserGuide.md
Labels: priority.Medium, severity.Low, type.DocumentationBug

#127 Specify meaning of appointments and next appointment in Sched command
  docs/UserGuide.md
  docs/images/NextAppointment.png
  docs/images/TotalAppointments.png
Labels: priority.Medium, type.DocumentationBug

#132 Add docs under known issues for issue #87
  docs/UserGuide.md
Labels: severity.Low, type.DocumentationBug

#133 Update MacOS bug in known issues
  docs/UserGuide.md
Labels: type.Bug, priority.Medium

#136 Update del sequence diagram in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
Labels: severity.VeryLow, type.DocumentationBug

#137 Formatting UG and DG and update NFR in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: severity.VeryLow

#134 Update dg appointments
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AppointmentClassDiagram.puml
  docs/diagrams/FindTagSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/AppointmentClassDiagram.png
  docs/images/FindTagSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/index.md
Labels: type.Task, priority.High, type.DocumentationBug

#139 Remove note on symbols and improve testing instructions
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, severity.Low, type.DocumentationBug

#140 Formatting UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/ViewSequenceDiagram.png
Labels: severity.VeryLow, type.DocumentationBug
